Link cellrank in docstrings
theislab/scvelo pull request #281
Opened 2020-09-19 23:43 UTC by michalk8

Hi @VolkerBergen ,

I believe you've discussed this with Marius a while back, sorry it took me so long.
@Marius1311 - is tie phrasing fine? I've tried to be very minimal.

closes #269

2020-09-21 07:05 UTC, Marius1311 requested changes

2020-09-21 07:05 UTC, Marius1311 commented on scvelo/tools/terminal_states.py
> +
Better: "An alternative option would be to use XXX or XXX, both of which make use of real Schur decompositions to handle non-symmetries in the transition matrix. These methods are also able to separate multiple initial/terminal states and to pick the most likely cells from each. "

2020-09-21 07:05 UTC, Marius1311 commented on scvelo/tools/transition_matrix.py
> +
Again, "An alternative option is given by XXX which takes into account uncertainty in the velocity vectors when computing transition probabilities.  "

2020-09-21 13:56 UTC, michalk8 commented
Changed it as you've suggested - should be good now.

2020-09-21 15:04 UTC, Marius1311 approved these changes

2020-09-21 15:04 UTC, Marius1311 commented
Looking good from my point of view. @VolkerBergen , could you take a look at this please?

2020-10-01 19:05 UTC, michalk8 commented
Ping @VolkerBergen

2020-10-02 07:39 UTC, Marius1311 commented
Would be great to merge this, it's only some very minor changes that only affect the docs. @VolkerBergen

2020-10-05 16:01 UTC, VolkerBergen commented
thank you, slightly modified and pushed.

2020-10-05 16:01 UTC, closed without merging

2020-10-05 18:16 UTC, Marius1311 commented
thanks Volker.